openapi: 3.0.0
info:
  title: Yarn Cart API - OpenAPI 3.0.0
  version: 1.0.0
servers:
  - url: 127.0.0.1:8080
tags:
  - name: Cart
paths:
  /cart:
    get:
      tags:
        - Cart
      summary: Returns current Yarns in cart
      responses:
        "200":
          description: JSON array of yarns
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    post:
      tags:
        - Cart
      summary: Adds a Yarn to the cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Yarn"
      responses:
        "201":
          description: Yarn added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Yarn"
        "400":
          description: Invalid input
  /cart/{product_id}:
    patch:
        tags:
          - Cart 
        summary: Update the Yarn quantity
        parameters:
          - in: path
            name: product_id
            required: true
            schema:
              type: string
            description: Product id of the yarn
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: integer
        responses:
          "200":
            description: Quantity updated successfully.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    yarn:
                      $ref: '#/components/schemas/Yarn'
                    quantity:
                      type: integer
          "404":
            description: Yarn not found.
    delete:
      tags:
        - Cart
      summary: Remove one item in the cart
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: string
          description: Product id of the yarn
      responses:
        "204":
          description: Yarn removed successfully
        "404":
          description: Yarn not found
components:
  schemas:
    Yarn:
      type: object
      properties:
        product_id:
          type: string
          x-go-type: primitive.ObjectID
          x-go-import:
            path: go.mongodb.org/mongo-driver/bson/primitive
          x-oapi-codegen-extra-tags:
            bson: _id,omitempty
        unit_name:
          type: string
        unit_color:
          type: string
        unit_price:
          type: number
        available:
          type: boolean
    Cart:
      type: object
      properties:
          items:
            type: array
            items:
              type: object
              properties:
                yarn:
                  $ref: '#/components/schemas/Yarn'
                quantity:
                  type: integer