// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// returns the catalog of all Yarns
	// (GET /catalog)
	GetCatalog(c *gin.Context)
	// Adds a Yarn to the catalog
	// (POST /catalog)
	PostCatalog(c *gin.Context)
	// Delete one item in the catalog
	// (DELETE /catalog/{product_id})
	DeleteCatalogProductId(c *gin.Context, productId string)
	// gets one yarn from the catalog
	// (GET /catalog/{product_id})
	GetCatalogProductId(c *gin.Context, productId string)
	// Update the Yarn availability
	// (PATCH /catalog/{product_id})
	PatchCatalogProductId(c *gin.Context, productId string)
	// Check if the service is running
	// (GET /check)
	GetCheck(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCatalog operation middleware
func (siw *ServerInterfaceWrapper) GetCatalog(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalog(c)
}

// PostCatalog operation middleware
func (siw *ServerInterfaceWrapper) PostCatalog(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCatalog(c)
}

// DeleteCatalogProductId operation middleware
func (siw *ServerInterfaceWrapper) DeleteCatalogProductId(c *gin.Context) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCatalogProductId(c, productId)
}

// GetCatalogProductId operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogProductId(c *gin.Context) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCatalogProductId(c, productId)
}

// PatchCatalogProductId operation middleware
func (siw *ServerInterfaceWrapper) PatchCatalogProductId(c *gin.Context) {

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchCatalogProductId(c, productId)
}

// GetCheck operation middleware
func (siw *ServerInterfaceWrapper) GetCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCheck(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/catalog", wrapper.GetCatalog)
	router.POST(options.BaseURL+"/catalog", wrapper.PostCatalog)
	router.DELETE(options.BaseURL+"/catalog/:product_id", wrapper.DeleteCatalogProductId)
	router.GET(options.BaseURL+"/catalog/:product_id", wrapper.GetCatalogProductId)
	router.PATCH(options.BaseURL+"/catalog/:product_id", wrapper.PatchCatalogProductId)
	router.GET(options.BaseURL+"/check", wrapper.GetCheck)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWTY8bNwz9KwLb49jjbXMI5pY2QOEeugsEPQTFYiFL9FjpjKhSHCPGwv+9EMfe9Wc3",
	"KZIgJ8sSRZHvPT7MIzjqE0WMkqF5hOxW2Ftd/mrFdtSWZWJKyBJQD4Jgf7z4kXEJDfxQPyerd5nq95Yj",
	"bCuQTUJowDLbDWyfN2jxAZ2UCI08e82ubejsosPyZ3dnQdSh1bSJyQ9OHoI/OM/CIbZQwcdJS5PQJ2LR",
	"zFZW0EBL055iS34xJW5rXU88hzVyvcgU68ShDxLWWF7QHLvETwfTWy17/lYfIZvCxJHHFuMEPwrbidhW",
	"yy/5oIGH4CvqC2BJxvaHGOTBUUd8Xvj+ONoer58mDu7wOA79AvkStmUrxCVpcJCCpaJtdhybN3dzMzG3",
	"CWNZ/TydTWdQwRo5By3/Rne2FVDCaFOABvZBBVPttHbPgmlR8S48WgkU5x4a+A1lr6kKGHOimEeOf5rN",
	"yo+jKBj1pk2pC07v1h8Uwr02X9Lb/glt2mN2HJKMXfz+7vYPowI0tDQbyzErWnnoe8sbaIBRBo7ZyArN",
	"rp0SarvOvNfwCkZi/3oaj/siQsoX+r2jfNTwPwNm+YX85rN6/axp+NaiKk0FRg+N8IDbM1pvvhito42c",
	"c6oytt6jN3lwDnNeDl23Kf28GlV1HD+Pa9sFb0JMg5yw/8b7bKwybYQORXCR9231pPn68dmHtuOjHQqe",
	"a+Kt7u9y3I135l7HiG2PglweOS16F2iCL2osdRXxQhnqYkrF1SoYeT00xFN+qgOsT9jf3p9x9+ocPEWG",
	"saf1Rbiv3YgkZklD9Cd4j2AYimiKM5oQX8S8eslavm9MZ199HtTjxhHdm9xVcuYF9GvktChZqSkpzJKp",
	"/wRykhW3uuCEZft7Jeir2/L/s87Zt7HOIXkrJ9M8/cRxnp5I5k/NpVSNtjyiErogm+sOukL3939+M2jA",
	"ZXyOq3uHvA4OTciGhxhHjg8L1FQmjGrKl6JLOPJ6r8iBO2igI2e7FWVpXs9e30CRza6Xx70An7467rf/",
	"BgAA///zWxhrUwsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
