openapi: 3.0.0
info:
  title: Yarn Cart API - OpenAPI 3.0.0
  version: 1.0.0
tags:
  - name: Cart
paths:
  /cart/check:
    get:
      summary: Check if the service is running
      responses:
        "200":
          description: Service is running
  /cart/new:
    post:
      tags:
        - Cart
      summary: Creates a new cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartItems"
      responses:
        "201":
          description: Cart created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart_id:
                    type: string
                    format: uuid
  /cart/{cart_id}:
    get:
      tags:
        - Cart
      summary: Returns current Yarns in cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
          description: Cart id
      responses:
        "200":
          description: JSON array of yarns
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    delete:
      tags:
        - Cart
      summary: Clear the cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Cart cleared successfully
    patch:
      tags:
        - Cart
      summary: Adds a Yarn to the cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
          description: Cart id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartItems"
      responses:
        "201":
          description: Yarn added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "400":
          description: Invalid input
  /cart/{cart_id}/{product_id}:
    delete:
      tags:
        - Cart
      summary: Remove one item in the cart
      parameters:
        - in: path
          name: cart_id
          required: true
          schema:
            type: string
          description: Cart id
        - in: path
          name: product_id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Yarn removed successfully
        "404":
          description: Yarn not found
components:
  schemas:
    Yarn:
      type: object
      properties:
        product_id:
          type: string
        unit_name:
          type: string
        unit_color:
          type: string
        unit_price:
          type: number
        available:
          type: boolean
    CartItems:
      type: array
      items:
        properties:
          yarn:
            $ref: "#/components/schemas/Yarn"
          quantity:
            type: integer
    Cart:
      type: object
      properties:
        cart_id:
          type: string
          format: uuid
        items:
          $ref: "#/components/schemas/CartItems"
