// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Cart defines model for Cart.
type Cart struct {
	CartId *openapi_types.UUID `json:"cart_id,omitempty"`
	Items  *[]CartItem         `json:"items,omitempty"`
}

// CartItem defines model for CartItem.
type CartItem struct {
	Quantity *int  `json:"quantity,omitempty"`
	Yarn     *Yarn `json:"yarn,omitempty"`
}

// Yarn defines model for Yarn.
type Yarn struct {
	Available *bool    `json:"available,omitempty"`
	ProductId *string  `json:"product_id,omitempty"`
	UnitColor *string  `json:"unit_color,omitempty"`
	UnitName  *string  `json:"unit_name,omitempty"`
	UnitPrice *float32 `json:"unit_price,omitempty"`
}

// PatchCartCartIdProductIdJSONBody defines parameters for PatchCartCartIdProductId.
type PatchCartCartIdProductIdJSONBody struct {
	Quantity *int `json:"quantity,omitempty"`
}

// PostCartNewJSONRequestBody defines body for PostCartNew for application/json ContentType.
type PostCartNewJSONRequestBody = CartItem

// PostCartCartIdJSONRequestBody defines body for PostCartCartId for application/json ContentType.
type PostCartCartIdJSONRequestBody = CartItem

// PatchCartCartIdProductIdJSONRequestBody defines body for PatchCartCartIdProductId for application/json ContentType.
type PatchCartCartIdProductIdJSONRequestBody PatchCartCartIdProductIdJSONBody
