// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates a new cart
	// (POST /cart/new)
	PostCartNew(c *gin.Context)
	// Clear the cart
	// (DELETE /cart/{cart_id})
	DeleteCartCartId(c *gin.Context, cartId string)
	// Returns current Yarns in cart
	// (GET /cart/{cart_id})
	GetCartCartId(c *gin.Context, cartId string)
	// Adds a Yarn to the cart
	// (POST /cart/{cart_id})
	PostCartCartId(c *gin.Context, cartId string)
	// Remove one item in the cart
	// (DELETE /cart/{cart_id}/{product_id})
	DeleteCartCartIdProductId(c *gin.Context, cartId string, productId string)
	// Update the Yarn quantity
	// (PATCH /cart/{cart_id}/{product_id})
	PatchCartCartIdProductId(c *gin.Context, cartId string, productId string)
	// Check if the service is running
	// (GET /check)
	GetCheck(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostCartNew operation middleware
func (siw *ServerInterfaceWrapper) PostCartNew(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCartNew(c)
}

// DeleteCartCartId operation middleware
func (siw *ServerInterfaceWrapper) DeleteCartCartId(c *gin.Context) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", c.Param("cart_id"), &cartId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cart_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCartCartId(c, cartId)
}

// GetCartCartId operation middleware
func (siw *ServerInterfaceWrapper) GetCartCartId(c *gin.Context) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", c.Param("cart_id"), &cartId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cart_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCartCartId(c, cartId)
}

// PostCartCartId operation middleware
func (siw *ServerInterfaceWrapper) PostCartCartId(c *gin.Context) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", c.Param("cart_id"), &cartId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cart_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCartCartId(c, cartId)
}

// DeleteCartCartIdProductId operation middleware
func (siw *ServerInterfaceWrapper) DeleteCartCartIdProductId(c *gin.Context) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", c.Param("cart_id"), &cartId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cart_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCartCartIdProductId(c, cartId, productId)
}

// PatchCartCartIdProductId operation middleware
func (siw *ServerInterfaceWrapper) PatchCartCartIdProductId(c *gin.Context) {

	var err error

	// ------------- Path parameter "cart_id" -------------
	var cartId string

	err = runtime.BindStyledParameterWithOptions("simple", "cart_id", c.Param("cart_id"), &cartId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cart_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithOptions("simple", "product_id", c.Param("product_id"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter product_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchCartCartIdProductId(c, cartId, productId)
}

// GetCheck operation middleware
func (siw *ServerInterfaceWrapper) GetCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCheck(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/cart/new", wrapper.PostCartNew)
	router.DELETE(options.BaseURL+"/cart/:cart_id", wrapper.DeleteCartCartId)
	router.GET(options.BaseURL+"/cart/:cart_id", wrapper.GetCartCartId)
	router.POST(options.BaseURL+"/cart/:cart_id", wrapper.PostCartCartId)
	router.DELETE(options.BaseURL+"/cart/:cart_id/:product_id", wrapper.DeleteCartCartIdProductId)
	router.PATCH(options.BaseURL+"/cart/:cart_id/:product_id", wrapper.PatchCartCartIdProductId)
	router.GET(options.BaseURL+"/check", wrapper.GetCheck)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWTW8jNwz9KwLb49R22pzmlrZA4R6StEEPQREEskTbys5IikQ5MAz/9wU1/p6x87EJ",
	"snsaQUOK5OPjkxagXO2dRUsRygVENcVa5uUfMhB/fXAeAxnMu0oGujeal2MXaklQQkpGQwE09wglRArG",
	"TmBZgCGss9Nm8XPAMZTwU38btb8K2ed4Q8KaPVdHyRDkHJbbDTd6QEVssbFuZfiYpCVDc16v3IwlnGBg",
	"v7kM9rlMbtmmM+rtyns/opxJU8lRhTshR85VKC07+eB0UmvUWigla+heucqF47+trPH4Xx+M2v1tUz3i",
	"atsV8JaxY5eNDXHGuSbBcIqL66H4RVx5tLz6rTfoDaCAGYZonIUSzvLOsgDn0UpvoIS1kZc0zVj0mSB9",
	"i08ZJhczhRgsScbZoYYSrl0kjneJT1BAwMeEkX53OndMOUtos5f0vjIq+/UforNbfr6cSlwwRzABNZQU",
	"EuaN6J2NTfN+HZy9Ku5bx6G7GRqjCsZTA3DuggooCbWISSmMcZyqqpmBmOpahjnbZZMopLD4JDgHjicn",
	"Ecr/m7m9Y4emF4tVjktOUmOFhO2e/Jn32TVjp3NLg6yRMPCpCzCcILcZCmjouCn+EOJiB65DFO5a8J83",
	"ebVxqFCGZ3BgE0FTPIJBARPsIOBfSKcq7cglF/lhCAzelfhdxPr75upSZDUVbixYA+MBlP8ipWCjUCkE",
	"tCRYFaIw9iiyp2f7M7H9sfTkLe3Mki21bk1HAecNm/bth3YmK6OFsT7RQeMvtGYhyUeSOzFMbUHpL7ZX",
	"26vU5bpx+wSCFJ1CtnNDv7uWZWAD1m7W2a1jHtaRGLtkdWtO+SThLAp+VfGEntI/L0lNO8aUt7+TfuxH",
	"WKUijGal4tLyi61477a9TSRe/tLsvu6fk47BB2Xzbe/etgD9s4olktetx0rvhczuHVD7v3xW7nk23BTU",
	"LUVTVF84xNErPht0Q7yf1g2GmVEoTBQhWbt+ru28M/goYRo+xi7r5SbHxZqdjXjfLb8GAAD//0+UW7tj",
	"DQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
