openapi: 3.0.0
info:
  title: Yarn Catalog API - OpenAPI 3.0.0
  version: 1.0.0
servers:
  - url: localhost:8081
tags:
  - name: Catalog
paths:
  /catalog:
    get:
      tags:
        - Catalog
      summary: returns the catalog of all Yarns
      responses:
        "200":
          description: JSON array of yarns
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Catalog"
    post:
      tags:
        - Catalog
      summary: Adds a Yarn to the catalog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                unit_name:
                  type: string
                unit_color:
                  type: string
                unit_price:
                  type: number
                available:
                  type: boolean
      responses:
        "201":
          description: Yarn added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Yarn"
        "400":
          description: Invalid input
  /catalog/{product_id}:
    get:
      tags:
        - Catalog
      summary: gets one yarn from the catalog
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: string
          description: Product id of the yarn
      responses:
        "200":
          description: JSON object of yarn
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Yarn"
        "404":
          description: Item not found
    patch:
      tags:
        - Catalog
      summary: Update the Yarn availability
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: string
          description: Product id of the yarn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                available:
                  type: boolean  
      responses:
        "200":
          description: Yarn updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Yarn"
        "404":
          description: Yarn not found.
        
    delete:
      tags:
        - Catalog
      summary: Delete one item in the catalog
      parameters:
        - in: path
          name: product_id
          required: true
          schema:
            type: string
          description: Product id of the yarn
      responses:
        "204":
          description: Yarn removed successfully
        "404":
          description: Yarn not found
components:
  schemas:
    Yarn:
      type: object
      properties:
        product_id:
          type: string
          x-go-type: primitive.ObjectID
          x-go-import:
            path: go.mongodb.org/mongo-driver/bson/primitive
          x-oapi-codegen-extra-tags:
            bson: _id,omitempty
        unit_name:
          type: string
        unit_color:
          type: string
        unit_price:
          type: number
        available:
          type: boolean
    Catalog:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Yarn'