// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package models

import "go.mongodb.org/mongo-driver/bson/primitive"

// Catalog defines model for Catalog.
type Catalog struct {
	Items *[]Yarn `json:"items,omitempty"`
}

// Yarn defines model for Yarn.
type Yarn struct {
	Available *bool               `json:"available,omitempty"`
	ProductId *primitive.ObjectID `bson:"_id,omitempty" json:"product_id,omitempty"`
	UnitColor *string             `json:"unit_color,omitempty"`
	UnitName  *string             `json:"unit_name,omitempty"`
	UnitPrice *float32            `json:"unit_price,omitempty"`
}

// PostCatalogJSONBody defines parameters for PostCatalog.
type PostCatalogJSONBody struct {
	Available *bool    `json:"available,omitempty"`
	UnitColor *string  `json:"unit_color,omitempty"`
	UnitName  *string  `json:"unit_name,omitempty"`
	UnitPrice *float32 `json:"unit_price,omitempty"`
}

// PatchCatalogProductIdJSONBody defines parameters for PatchCatalogProductId.
type PatchCatalogProductIdJSONBody struct {
	Available *bool `json:"available,omitempty"`
}

// PostCatalogJSONRequestBody defines body for PostCatalog for application/json ContentType.
type PostCatalogJSONRequestBody PostCatalogJSONBody

// PatchCatalogProductIdJSONRequestBody defines body for PatchCatalogProductId for application/json ContentType.
type PatchCatalogProductIdJSONRequestBody PatchCatalogProductIdJSONBody
